import type { Localized } from '../i18n/types';

export type AutomationChannel = 'email' | 'whatsapp' | 'documents' | 'data' | 'erp' | 'knowledge';

/** A business process expressed as trigger → engine → result. */
export interface AutomationFlow {
  id: string;
  channel: AutomationChannel;
  name: Localized;
  trigger: Localized;
  engine: Localized;
  result: Localized;
}

export const automationChannels: { id: AutomationChannel; label: Localized }[] = [
  { id: 'email', label: { en: 'Email', es: 'Email' } },
  { id: 'whatsapp', label: { en: 'WhatsApp', es: 'WhatsApp' } },
  { id: 'documents', label: { en: 'Documents', es: 'Documentos' } },
  { id: 'data', label: { en: 'Data', es: 'Datos' } },
  { id: 'erp', label: { en: 'ERP', es: 'ERP' } },
  { id: 'knowledge', label: { en: 'Knowledge', es: 'Conocimiento' } },
];

export const automationFlows: AutomationFlow[] = [
  {
    id: 'orders-email',
    channel: 'email',
    name: { en: 'Orders received by email', es: 'Pedidos recibidos por email' },
    trigger: { en: 'An order arrives in the inbox', es: 'Llega un pedido al buzón' },
    engine: { en: 'AI reads it and extracts the order lines', es: 'La IA lo lee y extrae las líneas' },
    result: { en: 'Order registered, no retyping', es: 'Pedido registrado sin reteclear' },
  },
  {
    id: 'orders-whatsapp',
    channel: 'whatsapp',
    name: { en: 'Orders received by WhatsApp', es: 'Pedidos recibidos por WhatsApp' },
    trigger: { en: 'A customer writes or sends a photo', es: 'Un cliente escribe o manda una foto' },
    engine: { en: 'Message and image are interpreted', es: 'Se interpretan mensaje e imagen' },
    result: { en: 'Structured order, ready to process', es: 'Pedido estructurado, listo para procesar' },
  },
  {
    id: 'display-restock',
    channel: 'whatsapp',
    name: { en: 'Display restocking by photo', es: 'Reposición de expositores por foto' },
    trigger: { en: 'A display is due for review', es: 'A un expositor le toca revisión' },
    engine: { en: 'WhatsApp asks for a photo; local AI counts every unit', es: 'WhatsApp pide una foto; la IA local cuenta cada unidad' },
    result: { en: 'The replenishment list, every morning', es: 'La lista de reposición, cada mañana' },
  },
  {
    id: 'doc-extraction',
    channel: 'documents',
    name: { en: 'Data extraction from documents', es: 'Extracción de datos de documentos' },
    trigger: { en: 'A document enters the flow', es: 'Entra un documento en el flujo' },
    engine: { en: 'OCR + AI locate the relevant fields', es: 'OCR + IA localizan los campos clave' },
    result: { en: 'Clean data instead of a scanned page', es: 'Datos limpios en lugar de una página escaneada' },
  },
  {
    id: 'pdf',
    channel: 'documents',
    name: { en: 'PDF processing', es: 'Procesamiento de PDFs' },
    trigger: { en: 'PDFs arrive by mail or folder', es: 'Llegan PDFs por correo o carpeta' },
    engine: { en: 'Parsed, split and classified', es: 'Se analizan, separan y clasifican' },
    result: { en: 'Content usable by other systems', es: 'Contenido utilizable por otros sistemas' },
  },
  {
    id: 'delivery-notes',
    channel: 'documents',
    name: { en: 'Delivery note (albarán) data', es: 'Datos de albaranes' },
    trigger: { en: 'A delivery note is received', es: 'Se recibe un albarán' },
    engine: { en: 'Items, quantities and references extracted', es: 'Se extraen artículos, cantidades y referencias' },
    result: { en: 'Ready to check or load into the ERP', es: 'Listo para cotejar o cargar en el ERP' },
  },
  {
    id: 'excel',
    channel: 'data',
    name: { en: 'Excel automation', es: 'Automatización de Excel' },
    trigger: { en: 'A spreadsheet that someone rebuilds by hand', es: 'Una hoja que alguien rehace a mano' },
    engine: { en: 'Read, transformed and regenerated by code', es: 'Leída, transformada y regenerada por código' },
    result: { en: 'The same report, without the manual hours', es: 'El mismo informe, sin las horas manuales' },
  },
  {
    id: 'erp',
    channel: 'erp',
    name: { en: 'ERP connection', es: 'Conexión con ERP' },
    trigger: { en: 'Data that has to reach — or leave — the ERP', es: 'Datos que deben entrar o salir del ERP' },
    engine: { en: 'Integration through its database or API', es: 'Integración por su base de datos o API' },
    result: { en: 'ERP in sync with the rest of the systems', es: 'ERP sincronizado con el resto de sistemas' },
  },
  {
    id: 'db-queries',
    channel: 'data',
    name: { en: 'Automatic database queries', es: 'Consultas automáticas a bases de datos' },
    trigger: { en: 'A recurring question about the business', es: 'Una pregunta recurrente sobre el negocio' },
    engine: { en: 'SQL runs on schedule or on demand', es: 'SQL que se ejecuta por horario o bajo demanda' },
    result: { en: 'The answer arrives without asking IT', es: 'La respuesta llega sin pedírsela a sistemas' },
  },
  {
    id: 'doc-generation',
    channel: 'documents',
    name: { en: 'Document generation', es: 'Generación de documentos' },
    trigger: { en: 'Data that has to become a document', es: 'Datos que deben convertirse en documento' },
    engine: { en: 'Templates filled by code', es: 'Plantillas rellenadas por código' },
    result: { en: 'Excel and PDF produced on their own', es: 'Excel y PDF generados solos' },
  },
  {
    id: 'classification',
    channel: 'knowledge',
    name: { en: 'Information classification', es: 'Clasificación de información' },
    trigger: { en: 'Mixed incoming information', es: 'Información entrante mezclada' },
    engine: { en: 'AI labels and routes each item', es: 'La IA etiqueta y enruta cada elemento' },
    result: { en: 'Everything lands where it belongs', es: 'Cada cosa llega a donde toca' },
  },
  {
    id: 'smart-search',
    channel: 'knowledge',
    name: { en: 'Smart search over documentation', es: 'Búsqueda inteligente en documentación' },
    trigger: { en: 'A question in plain language', es: 'Una pregunta en lenguaje natural' },
    engine: { en: 'RAG: semantic search + LLM', es: 'RAG: búsqueda semántica + LLM' },
    result: { en: 'An answer grounded in your own documents', es: 'Una respuesta basada en tus documentos' },
  },
  {
    id: 'supplier-prices',
    channel: 'documents',
    name: { en: 'Supplier price lists', es: 'Listas de precios de proveedores' },
    trigger: { en: 'Each supplier sends prices in its own format', es: 'Cada proveedor envía precios en su formato' },
    engine: { en: 'One parser per supplier cleans them in batch', es: 'Un parser por proveedor los limpia en lote' },
    result: { en: 'One merged file for the price updater', es: 'Un archivo fusionado para el actualizador de precios' },
  },
  {
    id: 'stock-alerts',
    channel: 'data',
    name: { en: 'Wholesaler stock watch', es: 'Vigilancia de stock en mayoristas' },
    trigger: { en: 'A product is out of stock everywhere', es: 'Un producto no tiene stock en ningún sitio' },
    engine: { en: 'Availability checked every hour', es: 'La disponibilidad se revisa cada hora' },
    result: { en: 'An e-mail the moment it is back', es: 'Un email en cuanto vuelve' },
  },
  {
    id: 'margins',
    channel: 'erp',
    name: { en: 'Gross-margin reporting', es: 'Informes de margen bruto' },
    trigger: { en: 'A quarter or year closes', es: 'Se cierra un trimestre o un año' },
    engine: { en: 'Sales and costs pulled from the ERP', es: 'Ventas y costes extraídos del ERP' },
    result: { en: 'Excel reports by customer, family and subfamily', es: 'Informes Excel por cliente, familia y subfamilia' },
  },
  {
    id: 'admin',
    channel: 'erp',
    name: { en: 'Administrative processes', es: 'Procesos administrativos' },
    trigger: { en: 'Repetitive back-office work', es: 'Trabajo administrativo repetitivo' },
    engine: { en: 'Each step mapped and scripted', es: 'Cada paso mapeado y automatizado' },
    result: { en: 'People review; the system executes', es: 'Las personas revisan; el sistema ejecuta' },
  },
];
